AppBundle\Entity\Giveaway:
    type: entity
    table: giveaway
    repositoryClass: AppBundle\Entity\GiveawayRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        price:
            type: string
            length: 255
        slug:
            type: string
            length: 128
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
        deletedAt:
              type: datetime
              nullable: true